name: CI

on:
  schedule:
    - cron: "6 6 * * 6"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      -
        name: Install sshpass
        run: brew install sshpass
      -
        name: Check sshpass installation
        run: which sshpass
